export enum BlockDevicesActionTypes {
  GET_SESSION_LIST = 'BLOCK_DEVICES_GET_ISCSI_SESSION_LIST',
  GET_IQN = 'BLOCK_DEVICES_GET_IQN',
  LOGIN_SESSION = 'BLOCK_DEVICES_LOGIN_SESSION',
  LOGOUT_SESSION = 'BLOCK_DEVICES_LOGOUT_SESSION',
  FC_LIP_SCAN = 'BLOCK_DEVICES_FC_LIP_SCAN',
}
