export enum BlockDevicesMutationTypes {
  SET_SESSION_LIST = 'BLOCK_DEVICES_SET_SESSION_LIST',
  SET_SESSION_ITEM = 'BLOCK_DEVICES_SET_SESSION_ITEM',
  DELETE_SESSION_ITEM = 'BLOCK_DEVICES_DELETE_SESSION_ITEM',
  SET_IQN = 'BLOCK_DEVICES_SET_IQN',
}
