export enum ActionsStateMutationTypes {
  ACTION_INITIATE = 'ACTIONS_STATE_ACTION_INITIATE',
  ACTION_ERROR = 'ACTIONS_STATE_ACTION_ERROR',
  ACTION_SUCCESS = 'ACTIONS_STATE_ACTION_SUCCESS',
  RESET_ACTIONS_STATE = 'ACTIONS_RESET_ACTIONS_STATE',
}
