export enum DashboardMutationTypes {
  // DATA
  SET_DATA = 'DASHBOARD_SET_DATA',

  // GRID
  SET_GRID = 'DASHBOARD_SET_GRID',
  ADD_GRID_ITEM = 'DASHBOARD_ADD_GRID_ITEM',
  REMOVE_GRID_ITEM = 'DASHBOARD_REMOVE_GRID_ITEM',
  SET_GRID_SETTINGS = 'DASHBOARD_SET_GRID_SETTINGS',
  RESET_GRID = 'DASHBOARD_RESET_GRID',
}
