export enum VirtualizationMutationTypes {
  // VM
  SET_VM_LIST = 'VIRTUALIZATION_SET_VM_LIST',
  SET_VM_ITEM = 'VIRTUALIZATION_SET_VM_ITEM',
  DELETE_VM_ITEM = 'VIRTUALIZATION_DELETE_VM_ITEM',

  // VIRTUAL NETWORK
  SET_VIRTUAL_NETWORK_LIST = 'VIRTUALIZATION_SET_VIRTUAL_NETWORK_LIST',
  SET_VIRTUAL_NETWORK_ITEM = 'VIRTUALIZATION_SET_VIRTUAL_NETWORK_ITEM',
  DELETE_VIRTUAL_NETWORK_ITEM = 'VIRTUALIZATION_DELETE_VIRTUAL_NETWORK_ITEM',
}
