export enum AppActionTypes {
  // INIT
  INIT = 'APP_INIT',

  // AUTH
  LOGIN = 'APP_LOGIN',
  LOGOUT = 'APP_LOGOUT',
  REFRESH = 'APP_REFRESH',

  // USER
  GET_CURRENT_USER = 'APP_GET_CURRENT_USER',

  // NOTIFICATIONS
  GET_NOTIFICATIONS = 'APP_GET_NOTIFICATIONS',
}
