export enum AppMutationTypes {
  // AUTH
  SET_AUTH = 'APP_SET_AUTH',

  // USER
  SET_CURRENT_USER = 'APP_SET_CURRENT_USER',

  // NOTIFICATIONS
  SET_NOTIFICATIONS = 'APP_SET_NOTIFICATIONS',

  // SETTINGS
  SET_SETTINGS = 'APP_SET_SETTINGS',
}
