export enum DevicesActionTypes {
  // INTERFACES
  GET_INTERFACE_LIST = 'DEVICES_GET_INTERFACE_LIST',
  CREATE_BRIDGE = 'DEVICES_CREATE_BRIDGE',
  DELETE_BRIDGE = 'DEVICES_DELETE_BRIDGE',
  GET_BRIDGE_LIST = 'DEVICES_GET_BRIDGE_LIST',
  TURN_ON_INTERFACE = 'DEVICES_TURN_ON_INTERFACE',
  TURN_OFF_INTERFACE = 'DEVICES_TURN_OFF_INTERFACE',

  // DISKS
  GET_DISK_LIST = 'DEVICES_GET_DISK_LIST',
  CREATE_DISK_PARTITION = 'DEVICES_CREATE_DISK_PARTITION',
  DELETE_DISK_PARTITION = 'DEVICES_DELETE_DISK_PARTITION',
}
