export enum DevicesMutationTypes {
  // INTERFACES
  SET_INTERFACE_LIST = 'DEVICES_SET_INTERFACE_LIST',
  SET_INTERFACE_ITEM = 'DEVICES_SET_INTERFACE_ITEM',
  DELETE_INTERFACE_ITEM = 'DEVICES_DELETE_INTERFACE_ITEM',
  SET_BRIDGE_LIST = 'DEVICES_SET_BRIDGE_LIST',

  // DISKS
  SET_DISK_LIST = 'DEVICES_SET_DISK_LIST',
  SET_DISK_ITEM = 'DEVICES_SET_DISK_ITEM',
  DELETE_DISK_ITEM = 'DEVICES_DELETE_DISK_ITEM',
}
