export enum StorageActionTypes {
  // STORAGE
  GET_STORAGE_LIST = 'STORAGE_GET_STORAGE_LIST',
  CREATE_STORAGE = 'STORAGE_CREATE_STORAGE',
  DELETE_STORAGE = 'STORAGE_DELETE_STORAGE',

  // VOLUME
  GET_VOLUME_LIST = 'STORAGE_GET_VOLUME_LIST',
  CREATE_VOLUME = 'STORAGE_CREATE_VOLUME',
  DELETE_VOLUME = 'STORAGE_DELETE_VOLUME',
  EXTEND_VOLUME = 'STORAGE_EXTEND_VOLUME',
  EDIT_VOLUME = 'STORAGE_EDIT_VOLUME',

  // IMAGE
  GET_IMAGE_LIST = 'STORAGE_GET_IMAGE_LIST',
  UPLOAD_IMAGE = 'STORAGE_UPLOAD_IMAGE',
  DELETE_IMAGE = 'STORAGE_DELETE_IMAGE',
}
