export enum StorageMutationTypes {
  // STORAGE
  SET_STORAGE_LIST = 'STORAGE_SET_STORAGE_LIST',
  SET_STORAGE_ITEM = 'STORAGE_SET_STORAGE_ITEM',
  DELETE_STORAGE_ITEM = 'STORAGE_DELETE_STORAGE_ITEM',

  // VOLUME
  SET_VOLUME_LIST = 'STORAGE_SET_VOLUME_LIST',
  SET_VOLUME_ITEM = 'STORAGE_SET_VOLUME_ITEM',
  DELETE_VOLUME_ITEM = 'STORAGE_DELETE_VOLUME_ITEM',

  // IMAGE
  SET_IMAGE_LIST = 'STORAGE_SET_IMAGE_LIST',
  SET_IMAGE_ITEM = 'STORAGE_SET_IMAGE_ITEM',
  DELETE_IMAGE_ITEM = 'STORAGE_DELETE_IMAGE_ITEM',
}
